; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = C:/Users/klaus/.cache/platformio-build

[env:featheresp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = featheresp32
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32Async/AsyncTCP @ 3.3.2
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    https://github.com/FastLED/FastLED.git#3.9.8
    tzapu/WiFiManager@2.0.17
lib_ignore =
  LittleFS_esp32
board_build.partitions = partition_custom.csv
board_build.filesystem = spiffs
build_flags = 
	-Ishows/
build_src_filter =
  +<*> 
  -<.git/> 
  -<.svn/> 
  -<example/> 
  -<examples/>
  -<test/> 
  -<tests/>
  -<target/>
  -<shows/>
  +<../shows/lightshows.cpp>